services:
  searxng:
    image: searxng/searxng:latest
    restart: unless-stopped
    ports:
      - "8888:8080"
    volumes:
      - searxng_data:/etc/searxng
    environment:
      - SEARXNG_BASE_URL=http://localhost:8888

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      # --- KRaft Settings ---
      # When initializing a new Kafka cluster in KRaft mode for the very first time, it requires a permanent,
      # unique ID. This ID is stored in the cluster's metadata and prevents nodes from accidentally joining the
      # wrong cluster
      # Use this command to get the Cluster ID: docker run --rm confluentinc/cp-kafka:latest kafka-storage random-uuid
      CLUSTER_ID: 1_3fypONTM2x4k4Hl_MMBg
      KAFKA_PROCESS_ROLES: 'broker,controller'  #In production use only one broker or controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'

      # --- Listener Definitions ---
      KAFKA_LISTENERS: 'INTERNAL://:29092,EXTERNAL://:9092,CONTROLLER://:9093'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka:29092,EXTERNAL://localhost:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT'

      # --- Standard Single-Node Settings ---
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  connect:
    image: debezium/connect:3.0.0.Final
    ports:
      - "8083:8083"
    depends_on: [kafka]
    environment:
      # Services inside this docker network (this service - debezium/connect) will use port 29092 to connect to kafka
      # Services outside this docker network (like the Node.js server running locally) will use the 9092 port instead
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses

volumes:
  searxng_data: